"""init schema

Revision ID: 4920e1f4cda9
Revises: 
Create Date: 2026-08-28 19:43:39.050399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4920e1f4cda9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector") # for embedding search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") #for fizzy search

    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', name='admin_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('client_phrases', sa.JSON(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ct_name', 'catalogs', ['name'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faq_search_text', 'faqs', ['search_text'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'REMOVED', name='book_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('PENDING', 'ONLINE', 'ON_SITE', name='payment_method'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_catalog_scheduled_at', 'bookings', ['catalog_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_bookings_catalog_id'), 'bookings', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=99), nullable=True),
    sa.Column('idempotence_key', sa.String(length=67), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotence_key'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index('idx_payatt_bk_id', 'payment_attempts', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_booking_id'), table_name='payment_attempts')
    op.drop_index('idx_payatt_bk_id', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_catalog_id'), table_name='bookings')
    op.drop_index('idx_bookings_catalog_scheduled_at', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_index('idx_faq_search_text', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index('idx_ct_name', table_name='catalogs')
    op.drop_table('catalogs')
    op.drop_table('admins')
    # ### end Alembic commands ###
