"""rename bookstatus in DB

Revision ID: 92a6298b5cef
Revises: fa3dd52d0e4b
Create Date: 2026-08-13 21:42:41.619095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92a6298b5cef'
down_revision: Union[str, Sequence[str], None] = 'fa3dd52d0e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE bookstatus RENAME TO book_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE book_status RENAME TO bookstatus")
    # ### end Alembic commands ###
