"""add new value to AdminRole

Revision ID: ba67daec88bc
Revises: 4920e1f4cda9
Create Date: 2026-09-01 00:32:45.225985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba67daec88bc'
down_revision: Union[str, Sequence[str], None] = '4920e1f4cda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_payatt_bk_id'), table_name='payment_attempts')
    op.create_index(op.f('ix_payment_attempts_booking_id'), 'payment_attempts', ['booking_id'], unique=False)

    op.execute("alter type admin_role add value 'USER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_booking_id'), table_name='payment_attempts')
    op.create_index(op.f('idx_payatt_bk_id'), 'payment_attempts', ['booking_id'], unique=False)
    # ### end Alembic commands ###
