"""init models

Revision ID: fa3dd52d0e4b
Revises: 
Create Date: 2026-08-08 18:44:30.467753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa3dd52d0e4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    payment_method_enum = postgresql.ENUM(
        "ONLINE",
        "ON_SITE",
        "PENDING",
        name="paymentmethod",
    )

    payment_method_enum.create(
        op.get_bind(),
        checkfirst=True,
    )

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=99), nullable=True),
    sa.Column('idempotence_key', sa.String(length=67), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotence_key'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index('idx_payatt_bk_id', 'payment_attempts', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_booking_id'), 'payment_attempts', ['booking_id'], unique=False)
    op.drop_table('pay_histories')
    op.add_column('bookings', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('payment_method', payment_method_enum, nullable=True))
    op.drop_index(op.f('idx_bk_ct_id'), table_name='bookings')
    op.drop_index(op.f('idx_bk_payment_id'), table_name='bookings')
    op.drop_index(op.f('idx_bk_us_id'), table_name='bookings')
    op.create_index('idx_bookings_catalog_scheduled_at', 'bookings', ['catalog_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_bookings_catalog_id'), 'bookings', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.alter_column('catalogs', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###

    op.execute(
        """
        update bookings
        SET scheduled_at = date+time
        where scheduled_at is null
        """
    )

    op.execute(
        """
        update bookings as b 
        set price = c.price
        from catalogs as c
        where c.id = b.catalog_id
        and b.price is null
        """
    )

    op.execute(
        """
        update bookings
        set payment_method = 'PENDING'
        where payment_method is null
        """
    )

    op.alter_column(
        "bookings",
        "scheduled_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "bookings",
        "price",
        nullable=False,
    )
    op.alter_column(
        "bookings",
        "payment_method",
        nullable=False,
    )

    op.drop_column('bookings', 'time')
    op.drop_column('bookings', 'date')
    op.drop_column('bookings', 'payment_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'duration',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('bookings', sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_catalog_id'), table_name='bookings')
    op.drop_index('idx_bookings_catalog_scheduled_at', table_name='bookings')
    op.create_index(op.f('idx_bk_us_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('idx_bk_payment_id'), 'bookings', ['payment_id'], unique=False)
    op.create_index(op.f('idx_bk_ct_id'), 'bookings', ['catalog_id'], unique=False)
    op.drop_column('bookings', 'payment_method')
    op.drop_column('bookings', 'price')
    op.drop_column('bookings', 'scheduled_at')
    op.create_table('pay_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('pay_histories_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pay_histories_pkey'))
    )
    op.drop_index(op.f('ix_payment_attempts_booking_id'), table_name='payment_attempts')
    op.drop_index('idx_payatt_bk_id', table_name='payment_attempts')
    op.drop_table('payment_attempts')
    # ### end Alembic commands ###